services:
  app-1:
    image: ghcr.io/team-hanseungil/nochu-be-nestjs:latest
    container_name: nochu-app-1
    ports:
      - "3001:3000"
    env_file: .env
    restart: unless-stopped

  app-2:
    image: ghcr.io/team-hanseungil/nochu-be-nestjs:latest
    container_name: nochu-app-2
    ports:
      - "3002:3000"
    env_file: .env
    restart: unless-stopped
